.changeset/many-penguins-beam.md, src/idl/IdlInstruction.ts, src/nodes/InstructionAccountNode.ts, src/nodes/InstructionNode.ts
As the new shank version will assume.
This is a breaking change so the library should be bumped accordingly.
=> Default optional account strategy to program ID

.changeset/wild-shoes-beg.md, src/nodes/InstructionNode.ts, src/renderers/js/GetJavaScriptRenderMapVisitor.ts, src/renderers/js/templates/instructionsPage.njk, src/renderers/js/templates/instructionsPageRemainingAccounts.njk, src/renderers/js/templates/instructionsPageResolvedInputs.njk, src/shared/RemainingAccounts.ts, src/shared/index.ts, test/package/src/generated/instructions/dummy.ts, test/testFile.cjs
Adds two strategy for resolving remaining accounts on a given instruction:
- `arg`, which expects an array of `PublicKey`, `Signer` or both as an (extra) argument, and use that arg to fill remaining accounts.
- `resolver` for custom remaining accounts resolution.
For example, imagine the following example that burns Compressed NFTs and accepts the "Proof" of the leaf to burn as remaining accounts.
```ts
await burn(umi, {
// ...
}).sendAndConfirm(umi);
```
Given an array of `PublicKey` as the Proof, before this PR we would need to do the following:
```ts
const proofs = [...];
await burn(umi, {
// ...
})
.addRemainingAccounts(proofs.map(pubkey) => {
pubkey,
isSigner: false,
isWritable: false,
})
.sendAndConfirm(umi);
```
After this PR, we can now pass the proof directly as an extra argument …
=> Add support for remaining accounts resolution

.changeset/fast-rats-impress.md, .changeset/many-hairs-buy.md, src/nodes/AccountNode.ts, src/renderers/js/templates/accountsPage.njk, src/renderers/rust/templates/accountsPage.njk, src/renderers/rust/templates/errorsPage.njk, test/packages/rust/Cargo.lock, test/packages/rust/Cargo.toml, test/packages/rust/src/generated/errors/mpl_candy_machine_core.rs, test/packages/rust/src/generated/errors/mpl_token_auth_rules.rs, test/packages/rust/src/generated/errors/mpl_token_metadata.rs
This PR includes two improvements to renderers:
1. Allow the account size property to be set to `null`
2. Simplify the traits definition for generate Rust errors enum
=> Improve account size and rust error traits

.changeset/eight-moons-bathe.md, src/renderers/rust/templates/errorsPage.njk, test/packages/rust/Cargo.lock, test/packages/rust/Cargo.toml, test/packages/rust/src/generated/errors/mpl_candy_machine_core.rs, test/packages/rust/src/generated/errors/mpl_token_auth_rules.rs, test/packages/rust/src/generated/errors/mpl_token_metadata.rs
This PR replaces the dependency on `spl-program-error` by deriving directly the traits included. The reason for this is that version `0.1.0`, which supports Solana `1.14`, does not export the dependent libraries.
=> Switch to use error traits

.changeset/brave-crabs-shave.md, src/renderers/rust/GetRustRenderMapVisitor.ts, src/renderers/rust/templates/errorsMod.njk
This PR adds a length test on the program errors to avoid exporting empty error enums.
=> Add program errors length test

.changeset/blue-zebras-wink.md, src/renderers/rust/templates/accountsPage.njk, test/packages/rust/src/generated/accounts/candy_machine.rs, test/packages/rust/src/generated/accounts/collection_authority_record.rs, test/packages/rust/src/generated/accounts/delegate_record.rs, test/packages/rust/src/generated/accounts/edition.rs, test/packages/rust/src/generated/accounts/edition_marker.rs, test/packages/rust/src/generated/accounts/frequency_account.rs, test/packages/rust/src/generated/accounts/master_edition_v1.rs, test/packages/rust/src/generated/accounts/master_edition_v2.rs, test/packages/rust/src/generated/accounts/metadata.rs, test/packages/rust/src/generated/accounts/reservation_list_v1.rs, test/packages/rust/src/generated/accounts/reservation_list_v2.rs, test/packages/rust/src/generated/accounts/token_owned_escrow.rs, test/packages/rust/src/generated/accounts/use_authority_record.rs
This PR adds a `from_bytes` helper to account types on the Rust client to make is easier to load an account.
Currently, we need to pass a mutable slice to `BorshDeserialize::deserialize(...)`:
```rust
let metadata_account = get_account(&mut context, &metadata).await;
let metadata: Metadata = Metadata::deserialize(&mut &metadata_account.data[..]).unwrap();
```
With the change proposed in this PR, the code is simplified:
```rust
let metadata_account = get_account(&mut context, &metadata).await;
let metadata: Metadata = Metadata::from_bytes(&metadata_account.data).unwrap();
```
=> Add bytes helper to account types on Rust client

.changeset/hot-moons-breathe.md, src/renderers/rust/templates/errorsPage.njk, test/packages/rust/src/generated/errors/mpl_candy_machine_core.rs, test/packages/rust/src/generated/errors/mpl_token_auth_rules.rs, test/packages/rust/src/generated/errors/mpl_token_metadata.rs
PR to add decimal indices to error comments. This can be helpful when debugging, since it would be easier to identify an error by its index from the documentation.
=> Add decimal indices to error comments in Rust client

.changeset/six-colts-dream.md, src/renderers/js/GetJavaScriptRenderMapVisitor.ts, src/renderers/js/RenderJavaScriptInstructionDefaults.ts
Currently, it can happen that `resolvedArgs` is used by a default value even though it's not actually being generated. This fixes it by using the `input` or `args` object instead when appropriate.
=> Fix argument object when resolving defaults in JS renderer

.changeset/twelve-cougars-smash.md, src/renderers/rust/templates/instructionsCpiPage.njk
This PR changes the Rust renderer to only generate the CPI accounts when the instruction expects accounts – i.e., the CPI account struct is not generated for instructions that to not take accounts.
=> Generate CPI accounts only when needed

.changeset/sixty-falcons-beg.md, .github/workflows/main.yml, src/renderers/rust/GetRustRenderMapVisitor.ts, src/renderers/rust/templates/accountsPage.njk, test/packages/rust/src/generated/accounts/delegate_record.rs, test/packages/rust/src/generated/accounts/edition_marker.rs, test/packages/rust/src/generated/accounts/frequency_account.rs, test/packages/rust/src/generated/accounts/master_edition_v1.rs, test/packages/rust/src/generated/accounts/master_edition_v2.rs, test/packages/rust/src/generated/accounts/metadata.rs, test/packages/rust/src/generated/types/hidden_settings.rs
This PR exposes the constant seeds used in PDA generation as a `PREFIX` field on account structs.
=> Add constant seeds

.changeset/shaggy-paws-jam.md, src/visitors/addPdasVisitor.ts, src/visitors/index.ts, test/visitors/addPdasVisitor.test.ts
Whilst we can already create PDA nodes linked to accounts using the `updateAccountsVisitor`, the `addPdasVisitor` allows us to add "ghost" PDA nodes to programs (i.e. not linked to any account).
```ts
kinobi.update(
addPdasVisitor({
myProgram: [
pdaNode('metadata', [
constantPdaSeedNodeFromString('metadata'),
programIdPdaSeedNode(),
variablePdaSeedNode('mint', publicKeyTypeNode()),
]),
]
})
);
```
=> Add a visitor that adds PDA nodes to programs

.changeset/four-pots-heal.md, src/renderers/rust/templates/accountsPage.njk, test/renderers/rust/_setup.ts, test/renderers/rust/accountsPage.test.ts
This PR fixes the seeds generation for PDA helpers when byte arrays are used on the Rust client.
=> Fix byte seeds

test/renderers/js-experimental/_setup.ts, test/renderers/js-experimental/accountsPage.test.ts, test/renderers/js-experimental/pdasPage.test.ts, test/renderers/js-experimental/programsPage.test.ts
- Refactors code comparison for render tests.
- Adds a test for empty seed PDAs in the accountsPage which generates fetch helpers for PDA-linked accounts.
No need for a changeset here since no actual logic has been changed, only tests.
=> Add accountsPage test for empty seed PDAs in js-experimental

.changeset/mighty-bats-relax.md, src/renderers/js-experimental/ImportMap.ts, src/renderers/js-experimental/fragments/programInstructions.ts, src/renderers/js-experimental/nameTransformers.ts, test/packages/js-experimental/src/generated/programs/mplCandyMachineCore.ts, test/packages/js-experimental/src/generated/programs/mplTokenAuthRules.ts, test/packages/js-experimental/src/generated/programs/mplTokenMetadata.ts, test/packages/js-experimental/src/generated/programs/splSystem.ts, test/renderers/js-experimental/programsPage.test.ts
This PR adds a new union type to each program, where each variant is an `instructionType` from its instruction types enum together with the parsed type. Eg:
```ts
export type ParsedMplTokenAuthRulesInstruction =
| ({
instructionType: MplTokenAuthRulesInstruction.CreateRuleSet;
} & ParsedCreateRuleSetInstruction)
| ({
instructionType: MplTokenAuthRulesInstruction.Validate;
} & ParsedValidateInstruction)
| ({
instructionType: MplTokenAuthRulesInstruction.CreateFrequencyRule;
} & ParsedCreateFrequencyRuleInstruction);
```
This allows consumers to parse instructions and then pass them around as eg `ParsedMplTokenAuthRulesInstruction`. They can then use `instructionType` to distinguish the variants, and then access the known parsed type. Passing around `ParsedCreateRuleSetInstruction` is …
=> Render a union type for parsed instructions in js-experimental

.changeset/rotten-horses-behave.md, src/renderers/js-experimental/fragments/programInstructions.ts, test/packages/js-experimental/src/generated/programs/mplCandyMachineCore.ts, test/packages/js-experimental/src/generated/programs/mplTokenAuthRules.ts, test/packages/js-experimental/src/generated/programs/mplTokenMetadata.ts, test/packages/js-experimental/src/generated/programs/splSystem.ts, test/renderers/js-experimental/programsPage.test.ts
This PR adds a type param to the parsed instruction union type, defaulting to the program address: 
```ts
export type ParsedMplCandyMachineCoreInstruction<
TProgram extends string = 'CndyV3LdqHUfDLmE5naZjVN8rBZz4tqhdefbAnjHG3JR'
> =
| ({
instructionType: MplCandyMachineCoreInstruction.Dummy;
} & ParsedDummyInstruction)
} & ParsedDummyInstruction<TProgram>)
...
```
This doesn't change any behaviour because the `ParsedXInstruction` types already use the same default `TProgram`. But it makes this link more explicit, and over-rideable if needed.
See https://github.com/metaplex-foundation/kinobi/pull/164#issuecomment-1971244887
=> Add a TProgram param to the ParsedInstruction union type in js-experimental

.changeset/lucky-numbers-glow.md, src/renderers/rust/getTypeManifestVisitor.ts, test/renderers/rust/definedTypesPage.test.ts
This PR adds support to `<prefix_type>PrefixString` types in Rust client.
=> Add support to prefix string type

.changeset/violet-clocks-pull.md, src/renderers/js-experimental/getTypeManifestVisitor.ts, src/renderers/js/getTypeManifestVisitor.ts, test/mpl_token_metadata.json, test/packages/js-experimental/src/generated/types/delegateArgs.ts, test/packages/js/src/generated/types/delegateArgs.ts
When setting a custom size on a data enum, the size codec/serializer was being generated but not imported.
=> Fix enum size import issue in JS renderers

.changeset/fast-camels-turn.md, src/nodes/InstructionRemainingAccountsNode.ts, src/renderers/js-experimental/fragments/instructionInputType.njk, src/renderers/js-experimental/fragments/instructionInputType.ts, src/renderers/js-experimental/fragments/instructionRemainingAccounts.ts, src/renderers/js-experimental/getTypeManifestVisitor.ts, src/renderers/js/getRenderMapVisitor.ts, src/renderers/js/getTypeManifestVisitor.ts, src/renderers/rust/getTypeManifestVisitor.ts, src/shared/utils.ts, src/visitors/getDebugStringVisitor.ts, test/packages/js-experimental/src/generated/instructions/addMemo.ts, test/packages/js-experimental/src/generated/instructions/createReservationList.ts, test/packages/js-experimental/src/generated/instructions/dummy.ts, test/packages/js/src/generated/instructions/addMemo.ts, test/testFile.cjs
This PR makes it possible to have an array of signers as remaining accounts on the JS experimental renderer.
It also refactors a few fragments along the way.
=> Add support for remaining account signers in JS experimental

.changeset/wicked-apples-tan.md, src/renderers/rust/getTypeManifestVisitor.ts, test/renderers/rust/instructionsPage.test.ts
This PR adds support to unsized string values in the Rust client by using the `RemainderStr` type.
=> Use remainder str type

.changeset/mighty-swans-rest.md, src/renderers/js-experimental/fragments/instructionFunction.ts
Fix an error in the JS Experimental renderer that causes a `Cannot find name 'args'` error.
This is because when an instruction has no arguments, the `args` variable won't be generated. However, when an instruction has remaining accounts that rely on the `argumentValueNode`, then we need that variable to exist.
The fix is to update the value of the `hasAnyArgs` helper to also include `remainingAccountsNodes` of values `argumentValueNode`.
=> Fix missing args variable error in JS Experimental
